INSERT INTO personas(id, nombre, vida, areas, biografia, premio) VALUES

(1, "Marie Curie", "1867-1934", "Física y química", "Marie Salomea Skłodowska-Curie​ (Varsovia, 7 de noviembre de 1867 - Passy, 4 de julio de 1934), más conocida como Marie Curie,​ fue una científica polaca nacionalizada francesa. Pionera en el campo de la radiactividad, fue la primera persona en recibir dos premios Nobel en distintas especialidades Física y Química​ y la primera mujer en ocupar el puesto de profesora en la Universidad de París. En 1995 fue sepultada con honores en el Panteón de París por méritos propios.", 1),

(2, "Albert Einstein", "1879-1955", "Física teórica", "Albert Einstein (en alemán [ˈalbɛɐ̯t ˈaɪnʃtaɪn]; Ulm, Imperio alemán, 14 de marzo de 1879-Princeton, Estados Unidos, 18 de abril de 1955) fue un físico alemán de origen judío, nacionalizado después suizo, austriaco y estadounidense. Es considerado el científico más conocido y popular del siglo XX​.", 3),

(3, "Malala Yousafzai", "1997-actualidad", NULL, "Malala Yousafzai (en pastún, ملاله یوسفزۍ /məˈlaːlə. jusəfˈzəj/) (Malālah Yūsafzay, Mingora, Pakistán, 12 de julio de 1997) es una activista, bloguera y estudiante universitaria1​ pakistaní residente en Inglaterra desde el atentado sufrido el 9 de octubre de 2012 con 15 años. Recibió el Premio Nobel de la Paz en 2014 a los 17 años,2​ convirtiéndose en la persona más joven en acceder a ese galardón en cualquiera de las categorías que se otorga.", 4),

(4, "Linus Pauling", "1901-1994", "Bioquímica, Medicina y Química cuántica", "Linus Carl Pauling (Portland, Oregón; 28 de febrero de 1901-Big Sur, California; 19 de agosto de 1994) fue un ingeniero químico, bioquímico y activista estadounidense. Él mismo se consideraba cristalógrafo, biólogo molecular e investigador médico. Fue uno de los primeros químicos cuánticos, y recibió el Premio Nobel de Química en 1954, por su trabajo en el que describía los enlaces químicos.", 5),

(5, "Doris Lessing", "1919-2013", "Literatura", "Doris Lessing, de soltera Doris May Tayler (Kermanshah, 22 de octubre de 1919 − Londres, 17 de noviembre de 2013),1​ que publicó también bajo el pseudónimo de Jane Somers, fue una escritora británica, ganadora del Premio Nobel de Literatura en 2007.", 6),

(6, "Amartya Sen", "1933-actualidad", "Economia", "Amartya Kumar Sen (en bengalí, অমর্ত্য কুমার সেন; en hindi, अमर्त्‍य कुमार सेन; translit.: Ômorto Kumar Shen) (nacido en Manikanj, Bangala (Raj británico), 3 de noviembre de 1933) es un filósofo y economista indio de etnia bengalí, galardonado con el Premio en Ciencias Económicas en memoria de Alfred Nobel en 1998", 6),

(7, "Antoine Becquerel", "1852-1908", "Radiactividad, fosforescencia y espectroscopia", "Antoine Henri Becquerel (París, 15 de diciembre de 1852-Le Croisic, 25 de agosto de 1908)1​ fue un físico francés descubridor de la radiactividad y galardonado con el Premio Nobel de Física del año 1903,2​ compartido con Pierre Curie y Maria Curie.", 2),

(8, "Pierre Curie", "1859-1906", "Física", "Pierre Curie (París, 15 de mayo de 1859 - íd. 19 de abril de 1906) fue un físico francés, pionero en el estudio de la radiactividad y descubridor de la piezoelectricidad, que fue galardonado con el Premio Nobel de Física en 1903, junto con su mujer: Marie Curie.", 2),

(9, "Kailash Satyarthi", "1954-actualidad", NULL, "Kailash Satyarthi (en hindi: ) (Vidisha, 11 de enero de 1954) es un activista indio por los derechos de los niños y ganador del Premio Nobel de la Paz en 2014. Desde los años 90 ha trabajado activamente con el movimiento indio contra el trabajo infantil. Su organización Bachpan Bachao Andolan ha liberado a más de 80.000 niños de varias formas de esclavitud, ayudándoles posteriormente para hacer posible su reintegración, rehabilitación y educación.​ Ganó el Premio Nobel de la Paz 2014 junto a Malala Yousafzai «por su lucha contra la represión de los niños y jóvenes, y por el derecho de todos los niños a la educación».", 4),

(10, "Nelson Mandela", "1918-2013", NULL, "Nelson Rolihlahla Mandela1​(IPA: [roli'ɬaɬa]) (Mvezo, Unión Sudafricana; 18 de julio de 1918-Johannesburgo, Gauteng, Sudáfrica; 5 de diciembre de 2013) fue un abogado, activista contra el apartheid, político y filántropo sudafricano que presidió su país de 1994 a 1999. Fue el primer mandatario de raza negra que encabezó el Poder Ejecutivo, y el primero en resultar elegido por sufragio universal en su país. Su gobierno se dedicó a desmontar la estructura social y política heredada del apartheid a través del combate del racismo institucionalizado, la pobreza y la desigualdad social, y la promoción de la reconciliación social. Como nacionalista africano y marxista, presidió el Congreso Nacional Africano (CNA) entre 1991 y 1997, y a nivel internacional fue secretario general del Movimiento de Países No Alineados entre 1998 y 2002.", 8),

(11, "Frederik de Klerk", "1936-actualidad", "Politica", "Frederik Willem de Klerk (Johannesburgo, 18 de marzo de 1936) es un político sudafricano, reconocido por liberar de prisión al activista Nelson Mandela y por contribuir, a su lado, a poner fin al régimen del apartheid, hecho por el cual ambos fueron galardonados con el Premio Nobel de la Paz de 1993 y con el Premio Príncipe de Asturias de Cooperación Internacional de 1992. De Klerk fue también vicepresidente durante la presidencia de Mandela.", 8),

(12, "Martin Luther King", "1929-1968", NULL, "Martin Luther King, Jr.Nota 1​ (Atlanta, 15 de enero de 1929-Memphis, 4 de abril de 1968) fue un pastor estadounidense de la Iglesia bautista1​ que desarrolló una labor crucial en Estados Unidos al frente del movimiento por los derechos civiles para los afroestadounidenses y que, además, participó como activista en numerosas protestas contra la Guerra de Vietnam y la pobreza en general.", 9),

(13, "Karl Landsteiner", "1868-1943", "Química", "Karl Landsteiner (Viena, 14 de junio de 1868-Nueva York, 26 de junio de 1943) fue un patólogo y biólogo austriaco, conocido por haber descubierto y tipificado los grupos sanguíneos. Se le concedió el Premio Nobel de Fisiología o Medicina en el año 1930.", 10),

(14, "Frederick Sanger", "1918-2013", "Bioquímica", "Frederick Sanger, OM, CH, CBE, FRS (Gloucestershire, Reino Unido, 13 de agosto de 1918 - Cambridge, Reino Unido, 19 de noviembre de 2013)1​ fue un bioquímico inglés dos veces laureado con el Premio Nobel de Química. Fue la cuarta persona del mundo en recibir dos premios Nobel, tras Marie Curie, Linus Pauling y John Bardeen.", 11),

(15, "Walter Gilbert", "1932-actualidad", "Bioquímica", "Walter Gilbert (Boston, Massachusetts, EEUU, 21 de marzo de 1932) es un físico, bioquímico y profesor universitario estadounidense galardonado con el Premio Nobel de Química del año 1980.", 12),

(16, "Paul Berg", "1926-actualidad", "Bioquímica", "Paul Naim Berg (30 de junio de 1926, Brooklyn, Nueva York) es un bioquímico y profesor emérito en la Universidad de Stanford.", 12),

(17, "Rainer Weiss", "1932-actualidad", "Física", "Rainer Weiss (29 de septiembre de 1932) es un físico estadounidense y profesor emérito de física en el MIT, conocido por su participación en el descubrimiento de las ondas gravitacionales, por el que fue galardonado, junto con Kip Thorne y Barry Barish, con el Premio Nobel de Física y con el Premio Princesa de Asturias de Investigación Científica y Técnica en el 2017. Su contribución al descubrimiento fue la invención y desarrollo de la técnica de interferometría láser, que es la operación básica de la colaboración científica LIGO responsable del descubrimiento de las ondas gravitacionales. Fue además presidente del Grupo de Trabajo Científico del satélite COBE.", 13),

(18, "Barry C. Barish", "1936-actualidad", "Física", "Barry C. Barish (27 de enero de 1936) es un físico experimental norteamericano, ganador (junto con Rainer Weiss y Kip Thorne) del Premio Nobel de Física, ""por sus contribuciones decisivas al detector LIGO y la observación de las ondas gravitacionales"") y del Premio Princesa de Asturias de Investigación Científica y Técnica,1​ ambos en el 2017. Es profesor emérito en la Cátedra Ronald y Maxine Linde de física del Instituto de Tecnología de California. Es un experto en ondas gravitacionales.", 13),

(19, "Kip S. Thorne", "1940-actualidad", "Física", "Kip Stephen Thorne (Logan, Utah, 1 de junio de 1940) es un físico teórico estadounidense, ganador del Premio Nobel de Física y del Premio Princesa de Asturias de Investigación Científica y Técnica, conocido por sus numerosas contribuciones en el campo de la física gravitacional y la astrofísica y por haber formado a toda una generación de científicos. Viejo amigo y colega de Stephen Hawking y Carl Sagan, ocupó la cátedra ""Profesor Feynman"" de Física Teórica en el Instituto Tecnológico de California hasta 2009.1​ Thorne es uno de los mayores expertos mundiales en las aplicaciones a la astrofísica de la Teoría de la Relatividad General de Albert Einstein. En la actualidad prosigue sus investigaciones científicas.", 13);